--- 
abstract: A Moose role for setting attributes from a simple configfile
author: 
  - Brandon L. Black, <blblack@gmail.com>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-SimpleConfig
no_index: 
  directory: 
    - inc
    - t
provides: 
  MooseX::SimpleConfig: 
    file: lib/MooseX/SimpleConfig.pm
    version: 0.02
requires: 
  Config::Any: 0
  Moose: 0
  MooseX::ConfigFromFile: 0
version: 0.02
