---
abstract: 'A Moose role for setting attributes from a simple configfile'
author:
  - 'Brandon L. Black, <blblack@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-SimpleConfig
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0.13
  Moose: 0.35
  MooseX::ConfigFromFile: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
